Changing some stuff

diff --git a/dwmc b/dwmc
--- a/dwmc
+++ b/dwmc
@@ -1,40 +1,40 @@
 #!/usr/bin/env sh
 
 signal() {
-	xsetroot -name "fsignal:$*"
+    xsetroot -name "fsignal:$*"
 }
 
 case $# in
 1)
-	case $1 in
-	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | togglevacant | togglepadding)
-		signal $1
-		;;
-	*)
-		echo "Unknown command or missing one argument."
-		exit 1
-		;;
-	esac
-	;;
+    case $1 in
+    setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | togglevacant | togglepadding)
+        signal $1
+        ;;
+    *)
+        echo "Unknown command or missing one argument."
+        exit 1
+        ;;
+    esac
+    ;;
 2)
-	case $1 in
-	view)
-		signal $1 ui $2
-		;;
-	viewex | toggleviewex | tagex | tagwithex | toggletagex | setlayoutex | focusstack | incnmaster | focusmon | tagmon | layoutmenu | quit)
-		signal $1 i $2
-		;;
-	setmfact)
-		signal $1 f $2
-		;;
-	*)
-		echo "Unknown command or one too many arguments."
-		exit 1
-		;;
-	esac
-	;;
+    case $1 in
+    view)
+        signal $1 ui $2
+        ;;
+    viewex | toggleviewex | tagex | tagwithex | toggletagex | setlayoutex | focusstack | incnmaster | focusmon | tagmon | layoutmenu | quit)
+        signal $1 i $2
+        ;;
+    setmfact)
+        signal $1 f $2
+        ;;
+    *)
+        echo "Unknown command or one too many arguments."
+        exit 1
+        ;;
+    esac
+    ;;
 *)
-	echo "Too many arguments."
-	exit 1
-	;;
+    echo "Too many arguments."
+    exit 1
+    ;;
 esac
